### ISSUE TITLE
prop-types should not be a peer dep

### ISSUE THREAD

**Issue by SamHH** [feathericons/react-feather#38]
`prop-types` is [listed as a peer dependency](https://github.com/feathericons/react-feather/blob/master/package.json#L49), however:

1. It isn't actually required at runtime as far as I can tell.
2. Many users (e.g. TypeScript users) won't be using it, so even if I'm wrong on the first point it probably shouldn't be required.

**Comment by carmelopullara** [comment]
This has been updated in version 2. `prop-types` is no more a peer dependency.
