### ISSUE TITLE
TS types aren't available

### ISSUE THREAD

**Issue by Glazy** [feathericons/react-feather#39]
Hi :wave:

Trying to use this library in a TypeScript project and running into an issue because the types aren't actually available. In `package.json` I can see that the types should be in `dist/index.d.ts` but that file is never actually copied across from `src` during build :+1:

Thanks!

**Comment by carmelopullara** [comment]
Just fixed!

**Comment by Glazy** [comment]
That was quick, thanks @carmelopullara :muscle:
