### ISSUE TITLE
[ PenTool ] Not available

### ISSUE THREAD

**Issue by LukyVj** [feathericons/react-feather#53]
Hello, we plan on using your lib at my company. 

However, the "PenTool" which we use, is not available.

**Comment by LukyVj** [comment]
https://github.com/feathericons/react-feather/issues/43

**Comment by LukyVj** [comment]
@carmelopullara :)

**Comment by carmelopullara** [comment]
@LukyVj updated!

**Comment by LukyVj** [comment]
You rock!
