### ISSUE TITLE
Forward ref to SVG graph

### ISSUE THREAD

**Issue by ikornienko** [feathericons/react-feather#56]
Some libraries rely on proper ref forwarding (e.g. see [tippy.js docs](https://github.com/atomiks/tippy.js-react#component-children) mentioning it). Unfortunately right now none of the icon components forward ref, which can be improved with something like

```js
import React, { forwardRef } from 'react';

const Activity = forwardRef((props, ref) => {
  const { color, size, ...otherProps } = props;
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      ...
      ref={ref}
    >
  ...
```

**Comment by katywings** [comment]
Related: #60

**Comment by carmelopullara** [comment]
Feature added.
