### ISSUE TITLE
Feature Request: Expose `strokeWidth` as an (optional) prop

### ISSUE THREAD

**Issue by zstix** [feathericons/react-feather#80]
## Description
On [the feather icons website](https://feathericons.com/) there are "customization" controls for previewing the icons. The options for the controls are:
* Size
* Stroke width
* Color

Currently, only `size` and `color` are [exposed as props](https://github.com/feathericons/react-feather/blob/master/src/index.d.ts#L4-L7). It looks like the `strokeWidth` for each icon is being hard-coded as `2` ([example](https://github.com/feathericons/react-feather/blob/master/src/icons/anchor.js#L14)).

This seems like a fairly straightforward adjustment. If you're accepting PRs, I'd be happy to add it!

**Comment by dexterthemsb** [comment]
You can pass strokeWidth as props. In the [example on line 17](https://github.com/feathericons/react-feather/blob/master/src/icons/anchor.js#L17), `{ ...rest }` is used. So any other props (other than exposed props) you pass are applied to the icon. If you pass strokeWidth as a prop it'll override the previously defined attribute of 2.
