### ISSUE TITLE
How can I set icon dynamically?

### ISSUE THREAD

**Issue by fabercs** [feathericons/react-feather#82]
In my app, icon names come from an external resource as strings for the navigation.

```
{
   "nav":[
      {
         "id":1,
         "title":"Home",
         "icon":"Home"
      }
   ]
}
```

I need something like;

`<Icon name={item.icon} />`

I couldn't find a way to create this icon dynamically, can't we do this?

**Comment by aelfric** [comment]
I haven't used it myself, but is this what you're looking for?

 https://github.com/feathericons/react-feather/issues/41#issuecomment-657059256

**Comment by fabercs** [comment]
@aelfric This is exactly what I was looking for, thank you!
