### ISSUE TITLE
Fix the React 18 dependency conflict

### ISSUE THREAD

**Issue by Ahsan-Ehtesham** [feathericons/react-feather#99]
Tried to use React Feather icons for React v18 but it shows dependency issue, kindly update the React Package

**Comment by outbackStack** [comment]
#98

**Comment by outbackStack** [comment]
#98

**Comment by The-Code-Monkey** [comment]
Looking like the creator has left I have an updated version

https://github.com/The-Code-Monkey/TechStack

Readme isnt updated yet but the npm package is 

@aw-web-design/react-feather

**Comment by wereHamster** [comment]
@The-Code-Monkey if the maintainer has abandoned the project, do we have any recourse to pick it up ourselves?

**Comment by The-Code-Monkey** [comment]
@wereHamster I do support it in my tech stack mono repo, feel free to add an issue or feature request on there if you need anything the package name is in the comment above
